#!/bin/sh
set -euo pipefail

CROND_ENV_FILTER="${CROND_ENV_FILTER:-"^EXPORT_"}"
ENVIRONMENT_VARS="$(printenv | (grep -E "${CROND_ENV_FILTER}" || true))"

if [[ "${CROND_ENV_FILTER}" = "^EXPORT_" ]]; then
    ENVIRONMENT_VARS="$(echo "${ENVIRONMENT_VARS}" | sed 's/^EXPORT_//g')"
fi

## Write with export to file which can be sourced in crontab entries
echo "${ENVIRONMENT_VARS}" | sed -E 's/^(.+)$/export \1/g' >> /etc/environment

## Add environment variables to the 0hourly cron which runs anacron for daily/weekly/monthly jobs
ENVIRONMENT_VARS_ESCAPED="$(echo "${ENVIRONMENT_VARS}" | sed -e 's/[\/&]/\\&/g' | sed ':begin;$!N;s/\n/\\n/;tbegin')"
sed -i 's/^PATH=\(.*\)$/PATH=\1\n'"$(echo "${ENVIRONMENT_VARS_ESCAPED}")"'/g' /etc/cron.d/0hourly

## If job config is specified setup /etc/cron.d/jobs
CROND_JOB_CONFIG="${CROND_JOB_CONFIG:-}"
if [[ -n "${CROND_JOB_CONFIG}" ]]; then
    echo "${CROND_JOB_CONFIG}" | base64 -d > /etc/cron.d/jobs
fi

exec "$@"
